version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t my-docker-app .
      - docker tag my-docker-app:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-docker-app:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-docker-app:latest
artifacts:
  files: '**/*'
