version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 888577039597.dkr.ecr.eu-west-1.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t network .
      - docker tag network:latest 888577039597.dkr.ecr.eu-west-1.amazonaws.com/network:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push 888577039597.dkr.ecr.eu-west-1.amazonaws.com/network:latest
      - echo "Saving build artifacts"
      - mkdir -p NetworkPipeline/BuildArtif
      - echo "Build successful" > NetworkPipeline/BuildArtif/build_info.txt

artifacts:
  files:
    - "NetworkPipeline/BuildArtif/**"
  discard-paths: no

