---
- name: Install Docker and Deploy Web App
  hosts: ec2_instances
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create app directory if it doesn't exist
      file:
        path: /home/ubuntu/webapp
        state: directory

    - name: Copy web application file to EC2 instance
      copy:
        src: /mnt/d/DBS/Assignment/Network/index.html
        dest: /home/ubuntu/webapp/index.html

    - name: Create Dockerfile
      copy:
        dest: /home/ubuntu/webapp/Dockerfile
        content: |
          FROM nginx:latest
          COPY index.html /usr/share/nginx/html/index.html
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]

    - name: Build Docker Image
      command: docker build -t webapp /home/ubuntu/webapp
      become: true

    - name: Run Docker Container
      docker_container:
        name: webapp_container
        image: webapp
        state: started
        restart_policy: always
        published_ports:
          - "80:80"

    - name: Check Docker container status
      command: docker ps
      register: docker_ps
      changed_when: false

    - name: Display Docker container status
      debug:
        msg: "{{ docker_ps.stdout }}"

