name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop and Remove Existing Docker Container (if using port 80)
        run: |
          ssh -i ~/.ssh/my-key.pem -t ec2-user@3.254.135.160 << 'EOF'
            CONTAINER_ID=$(docker ps -q -f "publish=80")
            if [ -n "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
            fi
          EOF

      - name: Load Docker Image on EC2
        run: |
          scp -i ~/.ssh/my-key.pem my-nginx.tar ec2-user@3.254.135.160:/home/ec2-user/

      - name: Load Docker Image on EC2
        run: |
          ssh -i ~/.ssh/my-key.pem -t ec2-user@3.254.135.160 << 'EOF'
            docker load -i /home/ec2-user/my-nginx.tar
          EOF

      - name: Run Docker Container
        run: |
          ssh -i ~/.ssh/my-key.pem -t ec2-user@3.254.135.160 << 'EOF'
            sudo docker run -d -p 80:80 --name my-web-app my-web-app
          EOF

